### ISSUE TITLE
Unknown command: 'refresh_data'

### ISSUE THREAD

**Issue by Gavin-yzg** [1251240000/StcokVisualization#17]
~/StcokVisualization# python3 manage.py refresh_data
Unknown command: 'refresh_data'
Type 'manage.py help' for usage.
这个命令无法运行呢，前面命令都正常

**Comment by 1251240000** [comment]
readme文件暂时还没更新，refresh_data这个命令现在被拆分了。可以执行python3 manage.py help查看stock app下的命令进行运行。

**Comment by Gavin-yzg** [comment]
Page not found (404)
Request Method: 	GET
Request URL: 	http://192.168.1.180:8000/

Using the URLconf defined in StockVisualization.urls, Django tried these URL patterns, in this order:

    do/
    api1/stock/

The empty path didn't match any of these.
运行起来报这个错是什么原因呢

**Comment by 1251240000** [comment]
项目前后端分离，runserver只是运行了后端应用。
如果熟悉linux环境，可以参考此[链接](https://www.runoob.com/django/django-nginx-uwsgi.html)部署应用。
